apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-lanchonete-55
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mysql/data
