version: '3.3'
services:
  redis:
    image: redis:latest
    container_name: api-production-redis
    ports:
      - "6379:6379"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - REDIS_HOST=api-production-redis
    ports:
      - 3000:3000
    depends_on:
      - redis
