apiVersion: v1
kind: Service
metadata:
  name: api-lanchonete-55-service
spec:
  selector:
    app: api-lanchonete-55
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
  type: LoadBalancer
