apiVersion: v1
kind: Secret
metadata:
  name: api-lanchonete-55-secrets
type: Opaque
data:
  DB_HOST: ZGItbGFuY2hvbmV0ZS01NS1zZXJ2aWNl
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: cm9vdA==
  DB_DATABASE: bGFuY2hvbmV0ZS01NQ==
  DB_PORT: MzMwNg==
  PORT: MzAwMA==
