apiVersion: v1
kind: Secret
metadata:
  name: db-lanchonete-55-secrets
type: Opaque
data:
  MYSQL_DATABASE: bGFuY2hvbmV0ZS01NQ==
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_PASSWORD: cm9vdA==
  MYSQL_ALLOW_EMPTY_PASSWORD: eWVz
  MYSQL_ROOT_HOST: JQ==
