openapi: "3.0.2"
info:
  version: 1.0.0
  title: API Orders
  description: >
    **Service responsible for the production line of orders**
paths:
  /production-orders:
    get:
      tags:
        - Production Orders
      summary: Get all open production orders
      parameters:
        - name: status
          in: query
          required: false
          description: Status of production orders to filter
          schema:
            type: string
      responses:
        200:
          description: Found production orders
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/ProductionOrderSchema"
                  message:
                    type: string
                    description: Sucess
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/InternalServerError"
  /production-orders/{productionOrderId}:
    patch:
      tags:
        - Production Orders
      summary: Get production order by id
      parameters:
        - name: productionOrderId
          in: path
          required: true
          description: Production Order id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  description: Status of the production order
      responses:
        200:
          description: Production Order ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                  message:
                    type: string
                    description: Sucess
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"
components:
  schemas:
    ProductionOrderSchema:
      type: object
      description: Full properties of a production order.
      properties:
        id:
          type: string
          description: Production Order id.
        status:
          type: string
          description: Production Order status.
        totalPrice:
          type: string
          description: Production Order total price.
        products:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: Product ID.
              name:
                type: string
                description: Product name.
              quantity:
                type: integer
                description: Quantity of the product.
  responses:
    BadRequest:
      description: Invalid Request
      content:
        "application/json":
          schema:
            properties:
              data:
                type: object
                properties:
                  stack:
                    type: string
              message:
                type: string
                title: Error message
                description: Describes a message informing a reason for the error
                example: "Email required"
    NotFound:
      description: Entity not found
      content:
        "application/json":
          schema:
            properties:
              data:
                type: object
                properties:
                  stack:
                    type: string
              message:
                type: string
                title: Error message
                description: Entity not found
                example: "Not Found"
    InternalServerError:
      description: Internal server error
      content:
        "application/json":
          schema:
            properties:
              data:
                type: object
                properties:
                  stack:
                    type: string
              message:
                type: string
                title: Error message
                description: Describes a message informing a reason for the error
                example: "Internal Server Error"
